version: '3'

services:
  e211book:
    image: phaustin/e211book:sep09
    build:
      context: e211book_image
    container_name: e211book_sep08
    labels:
      - "traefik.enable=false"
      

  e211hub:
    build: newhub_image
    image: phaustin/e211hub_img:sep09
    container_name: newe211hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:e211hub.eoastest5.xyz"
      - "traefik.port=8000"
    restart: on-failure
    networks:
      - proxy_aug07
      
      
networks:
    proxy_aug07:
      external: true

